apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
labels:
  - includeSelectors: true
    pairs:
      app: mealie
      app.kubernetes.io/part-of: mealie
resources:
  - namespace.yaml
  - app-data.yaml
  - db-secret.sops.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
