apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:1GRuE6/sHYKPrmicHyhkNGw4Tns1BZjW9rpnYYAcnFQ=,iv:KV933kmtPyZNy5IUTL4zdaFktrqT1rTJnmrVxlcsVj0=,tag:DnR1PM0vQLZohQfYqbe71w==,type:str]
    admin-user: ENC[AES256_GCM,data:7ltxkDx5DGE=,iv:UoDALqQAbXU/IPjwdy9Ccyc8r5m+e3MHMKdGDTTvy5Q=,tag:4dVkDfqiWUJ/frnKycv3lQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin
sops:
    age:
        - recipient: age1d06qu8eegt8wf8pewe8gw50jrrxt8wwzjhqhxgnl7f4myq9dzdxsdrps49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYzNvNVZiM2tVeEdSamxE
            MmRmWGY4MVpLMkoxT3k1UEVHOEhvVldyL1RBCjBhV0toQkFYQ2xPVHBzRzRRa3VM
            bGNGanRoQnFTemgyWko2bHlERG9WdVEKLS0tIFU4d2xnbDVNTk80QzE0RzZSWk1m
            WmlCWFU0RE5QZjdUcHNUYllwTE1lcnMK5WWengf/6rCheu3JZGWZu5isrk4UFda5
            E5YUO6MfHJ2uQ/o9uhacc0+PKs2pXv58X7AuTGjei9JpQfVSo852iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T23:15:51Z"
    mac: ENC[AES256_GCM,data:YFLzo7FXZBI6F5eimzxJYIB/5iJYMhmnPaE/LEjLkW0HLL9+mgUXzbXTKcdU26vnBvMR7O/BbcV/IV5m9aGJiHJ7kHLvrT3FNkZoJ6GFfNbv2YereqDxRvUwKYtIEMgrgW0f8ZQY01AvB1l5e8wjw9JZHg7rEMxLEGEFI6R1B5g=,iv:o+B227Gsvspns04jiOZGfoCLIcjOu/L6vTVtHRIe/Pc=,tag:l8hLJllAceJktwurJ2Re8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
