apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: kube-prometheus-values
    files:
      - values.yaml
resources:
  - namespace.yaml
  - grafana-admin-secret.sops.yaml
  - helmrepo.yaml
  - helmrelease.yaml
